### ISSUE TITLE
Adding a unit test for the order method of the OrderService class

### ISSUE THREAD

**Issue by mohsenebrahimy** [mohsenebrahimy/kiddo-restaurant#15]
- [x]  Create a test class for the OrderService interface.
- [x]  Then add a method to the OrderServiceTest class for testing the order method.
- [x]  In this unit test you should call the order method of the OrderService class
- [x]  Get the return type of the order method then assert the following items
- [x]  assert that the returned order is not null
- [x] assert that the status of the order is WAITING_FOR_COOK or whatever your enum is
- [x] assert that the id of the order is NOT null
- [x] assert that the order foods are not empty

**Comment by MaryamEbrahimi** [comment]
we've faced NullPointerException here and the test hasn't been passed
