### ISSUE TITLE
Implementing the OrderService interface

### ISSUE THREAD

**Issue by mohsenebrahimy** [mohsenebrahimy/kiddo-restaurant#22]
Create a new class named _OrderServiceImpl_ that implements the _OrderService_ interface. The interface has only one method and I will tell you how to implement this method in the next issue.
Also you need to add an instance variable of type _OrderRepository_ interface to the _OrderServiceImpl_ class. Whenever this class needs to interact with the repository will call a method of this instance variable. Note that the left hand side is _OrderRepository_ interface, but what we should put in the right hand side of this variable?

**Comment by MaryamEbrahimi** [comment]
?? we don't know
