### ISSUE TITLE
Implementing the order method of the OrderService interface

### ISSUE THREAD

**Issue by mohsenebrahimy** [mohsenebrahimy/kiddo-restaurant#23]
In the _OrderServiceImpl_ class that implemented the _OrderService_ interface, you should implement the sole method of the interface with the following steps:

- [x] Implement the method in the _OrderServiceImpl_ class.
- [x] This method accepts an order as its input parameter. You should change the status of the order to _"WAIT_FOR_COOK"_ or whatever your enum is.
- [x] At last you will call the save method of the _OrderRepository_ instance variable and return the order to the client.

**Comment by MaryamEbrahimi** [comment]
we can't return it to the client
