### ISSUE TITLE
Add a method to order a food for a specific customer

### ISSUE THREAD

**Issue by mohsenebrahimy** [mohsenebrahimy/kiddo-restaurant#75]
Add an overload of _order_ method to the _OrderService_ interface that accepts an order and a customer and persists the customer **if it doesn't exist**, and persist the order. In addition it also should update the orders field of the customer.

**Comment by mohsenebrahimy** [comment]
Please go to the issue #76 before resolving this one. That issue is the prerequisite of this issue.

**Comment by MaryamEbrahimi** [comment]
need help
